Feature/mariav/add team members list
vanessamarely/be-me pull request #14
Opened 2023-09-15 15:24 UTC by MariaVictoriaH

add member Maria Victoria

2023-09-20 04:48 UTC, DylasX commented
Este pr esta agregando una carpeta extra que no deberia estar, ajusta eso para darle merge

2023-09-20 04:49 UTC, DylasX requested changes

2023-09-20 04:49 UTC, DylasX commented on InRoute/members.md
> +Maria Victoria Higuita
Esto no es necesario
```suggestion
Maria Victoria Higuita
```

2023-09-25 20:39 UTC, DylasX commented
Aun sigue la carpeta presente

2023-10-24 13:37 UTC, closed without merging

2023-10-24 13:37 UTC, vanessamarely commented
Este archivo ya ha sido incluido en otro PR